//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_player.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Music_player.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01 {
            get {
                object obj = ResourceManager.GetObject("_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good boy
        ///Thấp thoáng ánh mắt đôi môi mang theo hương mê say
        ///Em cho anh tan trong miên man quên luôn đi đêm ngày
        ///Chạm nhẹ vội vàng hai ba giây nhưng con tim đâu hay
        ///Bối rối khẽ lên ngôi yêu thương đong đầy thật đầy
        ///Anh ngẩn ngơ cứ ngỡ
        ///(Đó chỉ là giấc mơ)
        ///Anh ngẩn ngơ cứ ngỡ
        ///(Như đang ngất ngây trong giấc mơ)
        ///Thật ngọt ngào êm dịu đắm chìm
        ///Phút chốc viết tương tư gieo nên thơ (yeah, hey)
        ///Có câu ca trong gió hát ngân nga, ru trời mây
        ///Nhẹ nhàng đón ban mai ngang qua trao nụ cười (trao nụ cười)
        ///Nắng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _01x {
            get {
                return ResourceManager.GetString("_01x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02 {
            get {
                object obj = ResourceManager.GetObject("_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có chàng trai viết lên cây
        ///Lời yêu thương cô gái ấy
        ///Mối tình như gió như mây
        ///Nhiều năm trôi qua vẫn thấy
        ///Giống như bức tranh vẽ bằng dịu êm ngày thơ
        ///Có khi trong tiềm thức ngỡ là mơ
        ///Câu chuyện đã rất xa xôi
        ///Niềm riêng không ai biết tới
        ///Hai người sống ở hai nơi
        ///Từ lâu không đi sát lối
        ///Chỉ thương có người vẫn hoài gìn giữ nhiều luyến lưu
        ///Mỗi khi nhớ đôi mắt biếc như thời chưa biết buồn đau
        ///Ngày cô ấy đi theo nơi phồn hoa
        ///Chàng trai bơ vơ từ xa trong tim hụt hẫng như mất một thứ gì
        ///Không ai hiểu  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _02x {
            get {
                return ResourceManager.GetString("_02x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03 {
            get {
                object obj = ResourceManager.GetObject("_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mưa trôi cả bầu trời nắng trượt theo những nỗi buồn
        ///Thấm ướt lệ sầu môi đắng vì đánh mất hy vọng
        ///Lần đầu gặp nhau dưới mưa trái tim rộn ràng bởi ánh nhìn
        ///Tình cảm dầm mưa thấm lâu em nào ngờ
        ///Mình hợp nhau đến như vậy thế nhưng không phải là yêu
        ///Và em muốn hỏi anh rằng chúng ta là thế nào
        ///Rồi lặng người đến vô tận trách sao được sự tàn nhẫn
        ///Anh trót vô tình thương em như là em gái
        ///Đừng lo lắng về em khi mà em vẫn còn yêu anh
        ///Càng xa lánh càng trống vắng tim cứ đau và nhớ lắm
        ///Đành phải buông hết tất [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _03x {
            get {
                return ResourceManager.GetString("_03x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _04 {
            get {
                object obj = ResourceManager.GetObject("_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _05 {
            get {
                object obj = ResourceManager.GetObject("_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06 {
            get {
                object obj = ResourceManager.GetObject("_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _07 {
            get {
                object obj = ResourceManager.GetObject("_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _08 {
            get {
                object obj = ResourceManager.GetObject("_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _09 {
            get {
                object obj = ResourceManager.GetObject("_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em on top, không phải trending
        ///Không phải YouTube, không phải trên Zing
        ///Anh on top, em ở trên anh
        ///Beat Touliver drop người ta gọi tên anh
        ///Big city
        ///Big city boi
        ///Big city
        ///Big city boi
        ///Big city
        ///Big city-Spacespeakers in da house make some mother fucker noise ay
        ///Thả tim đầy story em (thả)
        ///Nhắn tin đầy trong DM (slide)
        ///Có phiền thì sorry em (sorry)
        ///Đón, 10 giờ pm? (ten)
        ///Yea em thích coi sea game (dô)
        ///Hợp âm anh thích là Cm (đô)
        ///Xe em thích BM
        ///Việc anh thích là see em
        ///Trói em bằng cà vạt (trói)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11x {
            get {
                return ResourceManager.GetString("_11x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thật lòng em mơ, mơ cùng anh đi đến tận cùng
        ///Tận cùng chân mây, vượt núi cao hay biển sâu
        ///Biết mấy là yêu cho vừa, giết mấy thời gian cho vừa
        ///Khi yêu ta mơ về nhau
        ///Để thấy lắm lúc lòng mình nhẹ nhiều khi
        ///Muốn ném hết tất cả để mà đi
        ///Một lần được sống như những đứa nhóc không nhà
        ///Sớm thức dậy ở một nơi xa
        ///Bố em hút rất nhiều thuốc
        ///Mẹ em khóc mắt lệ nhoà
        ///Bố anh thì đi lại còn mẹ anh gọi điện thoại đến từng nhà
        ///Nhiều ngày rồi mình không về, không liên lạc được gì cả
        ///Chỉ vỏn vẹn lại mảnh giấy, &quot;đừng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12x {
            get {
                return ResourceManager.GetString("_12x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiên hà trong vũ trụ này hoài xa xôi
        ///Riêng mình ôm góc trời hạt ngọc đêm rơi rồi
        ///Ai cũng mong hóa giàu vậy nghèo phần ai?
        ///Sai từ ngay lúc đầu tình bạc như vôi
        ///Tiếc là mình không có nhau
        ///Tiếc là đời quá đớn đau
        ///Hay là duyên, mộng mơ không như lúc đầu
        ///Kiếp này ai đưa đón em?
        ///Kiếp này đôi tay lấm lem
        ///Sao mà mơ, trèo cao như hoa hải đường
        ///Vì lòng anh quá thương em, quá yêu em
        ///Nhớ thương em, anh đợi em về
        ///Thề rằng nếu lỡ mai này, có sum vầy
        ///Vẽ ngôi nhà, bóng hình em trong đấy
        ///Vậy mà em nỡ ra đi
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _13x {
            get {
                return ResourceManager.GetString("_13x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đập vỡ cây đàn giận đời đập vỡ cây đàn
        ///Người ơi người ơi tình ơi tình ơi
        ///Đập vỡ cây đàn giận đời bạc trắng như vôi
        ///Giận người điên đảo quên lời
        ///Đập vỡ cây đàn giận người con gái yêu đàn
        ///Buồn ơi buồn ơi làm sao để nguôi
        ///Đập vỡ cây đàn giận người đổi trắng thay đen
        ///Giận đời trở như bàn tay
        ///Chuyện ngày qua tôi gặp người con gái ớ
        ///Mang giọng ca thật buồn (mang giọng ca thật buồn)
        ///Em bảo tôi rằng anh đi học đàn (em bảo tôi rằng)
        ///Để đàn theo lúc em ca những ngày hoa mộng đời ta (hoa mộng đời ta)
        ///Tôi y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _21x {
            get {
                return ResourceManager.GetString("_21x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phận là con gái chưa một lần yêu ai
        ///Nhìn về tương lai mà thấy như sông rộng đường dài
        ///Cảnh nhà neo đơn bầy em chưa lớn
        ///Trĩu đôi vai gánh nhọc nhằn
        ///Thầy mẹ thương em nhờ tìm người se duyên
        ///Lòng cầu mong em đậu bến cho yên một bóng thuyền
        ///Lứa đôi tình duyên còn chưa lưu luyến
        ///Sợ người ta đến em khóc sau bao lời khuyên
        ///Chưa yêu lần nào biết ra làm sao
        ///Biết trong tình yêu như thế nào
        ///Sông sâu là bao nào đo được đâu
        ///Lòng người ta ai biết có dài lâu
        ///Qua bao thời gian sống trong bình an
        ///Lỡ yêu người t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _22x {
            get {
                return ResourceManager.GetString("_22x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23 {
            get {
                object obj = ResourceManager.GetObject("_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồn lỡ sa vào đôi mắt em
        ///Chiều nao xõa tóc ngồi bên rèm
        ///Thầm ước nhưng nào đâu dám nói
        ///Khép tâm tư lại thôi
        ///Đường hoa vẫn chưa mở lối
        ///
        ///Đời lắm phong trần tay trắng tay
        ///Trời đông ngại gió lùa vai gầy
        ///Lầu kín trăng về không lối chiếu
        ///Gác cao ngăn niềm yêu
        ///Thì thôi mơ ước chi nhiều
        ///
        ///Bên nhau sao tình xa vạn lý cách biệt mấy sơn khê
        ///Ngày đi mắt em xanh biển sâu, mắt tôi rưng rưng sầu
        ///Lặng nghe tiếng pháo tiễn ai qua cầu
        ///
        ///Đường phố muôn màu sao thiếu em
        ///Về đâu làn tóc xõa bên rèm
        ///Lầu vắng không [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _23x {
            get {
                return ResourceManager.GetString("_23x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25 {
            get {
                object obj = ResourceManager.GetObject("_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26 {
            get {
                object obj = ResourceManager.GetObject("_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _27 {
            get {
                object obj = ResourceManager.GetObject("_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28 {
            get {
                object obj = ResourceManager.GetObject("_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _29 {
            get {
                object obj = ResourceManager.GetObject("_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _30 {
            get {
                object obj = ResourceManager.GetObject("_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe đạp lách cách tôi vẫn chưa quen
        ///Đường thì tối chơi vơi còn tôi vẫn cứ đứng đợi
        ///Em nhẹ bước đến mi đã thôi hoen
        ///Trời trở gió heo may vì tôi đã lỡ yêu em
        ///Cũng may đường về nhà em quá xa
        ///Tôi mới được trông ngóng em buông lời hát
        ///Nhớ thương ngại ngùng nhìn em thoáng qua
        ///Hạ ơi đừng trôi mãi, mặc kệ em với tôi đi về
        ///Mới chỉ nhìn em khóc, tôi bỗng chợt nhận ra đã yêu em rồi
        ///Sáng trong cho mây ngừng trôi
        ///Rọi ánh mắt em trong lòng tôi
        ///Ngập ngừng chưa nói
        ///Mai sau để cho anh ngóng e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _31x {
            get {
                return ResourceManager.GetString("_31x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uây uây uây uây
        ///Sao mới gặp lần đầu mà đầu mình quay quay
        ///Anh ơi anh à
        ///Anh bỏ bùa gì mà lại làm em yêu vậy
        ///Bae bae bae bae
        ///Em nói từ đầu baby can you stay
        ///Mai đi coi ngày
        ///Xem cưới ngày nào thì nhà mình đông con vậy
        ///Nếu như một câu nói có thể khiến anh vui
        ///Sẽ suốt ngày luôn nói không ngừng để anh cười
        ///Nếu em làm như thế trông em có hâm không (điên điên điên lắm)
        ///Đem ngay vô nhà thương đem ngay vô nhà thương
        ///Đem ngay vô nhà anh để thương
        ///Giây phút em gặp anh là em biết em see tình
        ///Tình tình tình [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _32x {
            get {
                return ResourceManager.GetString("_32x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _33 {
            get {
                object obj = ResourceManager.GetObject("_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đón em về nhà sau buổi chiều tăng ca
        ///Đoạn đường vẫn thế sao hôm nay xa quá
        ///Rồi bỗng nhiên em không muốn về nhà
        ///Rồi bỗng nhiên anh cũng muốn đi xa
        ///Mình sống giữa lòng Hà Nội nhộn nhịp em ơi
        ///Mà đôi khi thấy lòng mình chơi vơi
        ///Dòng người đảo điên đôi khi khiến ta rối bời
        ///Hay là cứ theo anh mình đi đến nơi
        ///Bỏ em vào balo đưa em ra khỏi thủ đô
        ///Mình cùng rời thành phố tránh những làn khói ô tô
        ///Xây một căn nhà gỗ ở mãi xa tận ngoại ô
        ///Vứt hết những bão tố giữa chốn Hà Nội đông đúc xô bồ
        ///Gạt bỏ muộn phiề [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _33x {
            get {
                return ResourceManager.GetString("_33x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34 {
            get {
                object obj = ResourceManager.GetObject("_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _35 {
            get {
                object obj = ResourceManager.GetObject("_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _36 {
            get {
                object obj = ResourceManager.GetObject("_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37 {
            get {
                object obj = ResourceManager.GetObject("_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _38 {
            get {
                object obj = ResourceManager.GetObject("_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39 {
            get {
                object obj = ResourceManager.GetObject("_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love it when you call me señorita
        ///I wish I could pretend I didn&apos;t need ya
        ///But every touch is ooh, la-la-la
        ///It&apos;s true, la-la-la
        ///Ooh, I should be running
        ///Ooh, you keep me coming for ya
        ///Land in Miami
        ///The air was hot from summer rain
        ///Sweat dripping off me
        ///Before I even knew her name, la-la-la
        ///It felt like ooh, la-la-la
        ///Yeah, no
        ///Sapphire moonlight
        ///We danced for hours in the sand
        ///Tequila sunrise
        ///Her body fit right in my hands, la-la-la
        ///It felt like ooh, la-la-la, yeah
        ///I love it when you call me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _41x {
            get {
                return ResourceManager.GetString("_41x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42 {
            get {
                object obj = ResourceManager.GetObject("_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club isn&apos;t the best place to find a lover
        ///So the bar is where I go
        ///Me and my friends at the table doing shots
        ///Drinking fast and then we talk slow
        ///And you come over and start up a conversation with just me
        ///And trust me I&apos;ll give it a chance now
        ///Take my hand, stop, put Van the Man on the jukebox
        ///And then we start to dance, and now I&apos;m singing like
        ///Girl, you know I want your love
        ///Your love was handmade for somebody like me
        ///Come on now, follow my lead
        ///I may be crazy, don&apos;t mind me
        ///Say, boy, let&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _42x {
            get {
                return ResourceManager.GetString("_42x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _43 {
            get {
                object obj = ResourceManager.GetObject("_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I miss the days when life was so simple
        ///Felt like the glass was always half full
        ///Where did that go?
        ///And every second with you was so special
        ///Back when we didn&apos;t fear the unknowns
        ///But that was long ago
        ///Who can say where the path will go?
        ///Philosophers guess but they just don&apos;t know
        ///Maybe that&apos;s why
        ///We had our head in the clouds
        ///Thought we had it all figured out
        ///Planning to fly away
        ///To escape everything on the ground
        ///But like a plane up in space
        ///We slowly drifted away
        ///And every plan that we made [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43x {
            get {
                return ResourceManager.GetString("_43x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _44 {
            get {
                object obj = ResourceManager.GetObject("_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45 {
            get {
                object obj = ResourceManager.GetObject("_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _46 {
            get {
                object obj = ResourceManager.GetObject("_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _47 {
            get {
                object obj = ResourceManager.GetObject("_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48 {
            get {
                object obj = ResourceManager.GetObject("_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _49 {
            get {
                object obj = ResourceManager.GetObject("_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50 {
            get {
                object obj = ResourceManager.GetObject("_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51 {
            get {
                object obj = ResourceManager.GetObject("_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLACKPINK
        ///BLACKPINK
        ///BLACKPINK
        ///BLACKPINK
        ///Kick in the door, waving the coco&apos;
        ///팝콘이나 챙겨 껴들 생각 말고
        ///I talk that talk, runways I walk-walk
        ///눈 감고, pop-pop, 안 봐도 척
        ///One by one, then two by two
        ///내 손끝 툭 하나에 다 무너지는 중
        ///가짜 쇼 치곤 화려했지
        ///Makes no sense, you couldn&apos;t get a dollar out of me
        ///자, 오늘 밤이야, 난 독을 품은 꽃
        ///네 혼을 빼앗은 다음, look what you made us do
        ///천천히 널 잠재울 fire
        ///잔인할 만큼 아름다워 (I bring the pain like)
        ///This that pink venom, this that pink venom
        ///This that pink venom (get &apos;em, get &apos;em, get &apos;em)
        ///Straight to ya dome like wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _51x {
            get {
                return ResourceManager.GetString("_51x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52 {
            get {
                object obj = ResourceManager.GetObject("_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Cause I-I-I&apos;m in the stars tonight
        ///So watch me bring the fire and set the night alight
        ///Shoes on, get up in the morn&apos;
        ///Cup of milk, let&apos;s rock and roll
        ///King Kong, kick the drum, rolling on like a Rolling Stone
        ///Sing song when I&apos;m walking home
        ///Jump up to the top, LeBron
        ///Ding dong, call me on my phone
        ///Ice tea and a game of ping pong, huh
        ///This is getting heavy
        ///Can you hear the bass boom? I&apos;m ready (woo hoo)
        ///Life is sweet as honey
        ///Yeah, this beat cha-ching like money, huh
        ///Disco overload, I&apos;m into tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _52x {
            get {
                return ResourceManager.GetString("_52x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53 {
            get {
                object obj = ResourceManager.GetObject("_53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeah, yeah, yeah
        ///Blackpink in your area!
        ///Yeah, yeah, yeah
        ///천사 같은 &quot;hi&quot; 끝엔 악마 같은 &quot;bye&quot;
        ///매번 미칠듯한 high 뒤엔 뱉어야 하는 price
        ///이건 답이 없는 test
        ///매번 속더라도 yes
        ///딱한 감정의 노예
        ///얼어 죽을 사랑해 yeah
        ///Here I come kick in the door, uh
        ///가장 독한 걸로 줘 uh
        ///뻔하디 뻔한 그 love (love)
        ///더 내놔봐 give me some more
        ///알아서 매달려 벼랑 끝에
        ///한마디면 또 like 헤벌레 해
        ///그 따뜻한 떨림이 새빨간 설렘이
        ///마치 heaven 같겠지만
        ///You might not get in it
        ///Look at me, look at you
        ///누가 더 아플까
        ///You smart (you smart) 누가 you are
        ///두 눈에 피눈물 흐르게 된다면
        ///So sorry (so sorry) 누가 you are
        ///나 어떡해 나약한 날 견딜 수 없어
        ///애써 두 눈을 가 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _53x {
            get {
                return ResourceManager.GetString("_53x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _54 {
            get {
                object obj = ResourceManager.GetObject("_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _55 {
            get {
                object obj = ResourceManager.GetObject("_55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _56 {
            get {
                object obj = ResourceManager.GetObject("_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57 {
            get {
                object obj = ResourceManager.GetObject("_57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _58 {
            get {
                object obj = ResourceManager.GetObject("_58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _59 {
            get {
                object obj = ResourceManager.GetObject("_59", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _60 {
            get {
                object obj = ResourceManager.GetObject("_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bubble_chat {
            get {
                object obj = ResourceManager.GetObject("bubble_chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap empty_star {
            get {
                object obj = ResourceManager.GetObject("empty_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ipiccy_image {
            get {
                object obj = ResourceManager.GetObject("ipiccy_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rate {
            get {
                object obj = ResourceManager.GetObject("rate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_star {
            get {
                object obj = ResourceManager.GetObject("yellow_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
